### ISSUE TITLE
Change favicon from TL to BL during Marine Streams

### ISSUE THREAD

**Issue by r2dev2** [LiveTL/LiveTL#14]
Add a feature in which if the streamer is detected to be Houshou Marine, the favicon is changed to BL. A BL favicon is in ``img/blfavicon.ico``.

**Comment by yoyoyonono** [comment]
I'll give it a go

**Comment by r2dev2** [comment]
Solved in #126

**Comment by r2dev2** [comment]
Reopening because this functionality is missing in the new rewrite.

**Comment by ChrRubin** [comment]
a37bbfd conflicts with #232 by the way. I had set the favicon on the Popout component for whenever the FF bug gets fixed, but if you wanna ignore it you can just remove the `<svelte:head>` tag from the Popout component for a quick fix.
