### ISSUE TITLE
New layout request for Chat Side

### ISSUE THREAD

**Issue by Nandaka** [LiveTL/LiveTL#143]
**Is your feature request related to a problem? Please describe.**
Sometimes I want to watch 2 streams, but I only have 1 monitor.
Current layout for left/right will make the video quite small. 
![image](https://user-images.githubusercontent.com/836867/104814298-1e59f180-5849-11eb-853c-ca42d2c3cc37.png)

Portrail will make the chat quite small.
![image](https://user-images.githubusercontent.com/836867/104814280-02eee680-5849-11eb-916b-f75b16cee66a.png)

**Describe the solution you'd like**
Is it possible to have additional layout for the chat something like this (rough edit using chrome dev tool):
![image](https://user-images.githubusercontent.com/836867/104814239-d0dd8480-5848-11eb-9bcf-1cb6b2a7e3a0.png)

Comparison with edited and original.
![image](https://user-images.githubusercontent.com/836867/104814326-45b0be80-5849-11eb-9d39-0a7462712eae.png)

**Comment by r2dev2** [comment]
The extension is currently undergoing a full rewrite so we want to hold off from implementing very large changes as of now. In the rewritten extension, we'll try to add such a layout. For now, if you want to watch multiple streams, I'd recommend you to either use [holotools](https://hololive.jetri.co/#/), or to use popout chat.

**Comment by KentoNishi** [comment]
This layout is much more feasible now that we've done the rewrite! I'll keep it in my "will get to it eventually" list

**Comment by KentoNishi** [comment]
![image](https://user-images.githubusercontent.com/38841491/118722237-c88a5b80-b7e0-11eb-85c6-59eb757587b5.png)

**Comment by KentoNishi** [comment]
![image](https://user-images.githubusercontent.com/38841491/118723275-0e93ef00-b7e2-11eb-95ff-c57ebba67046.png)
