### ISSUE TITLE
YouTube UI language selector

### ISSUE THREAD

**Issue by Candygoblen123** [LiveTL/LiveTL#155]
**Is your feature request related to a problem? Please describe.**
The YouTube UI will always display the region language in the extension, despite any user settings.  

**Describe the solution you'd like**
A language selector in LiveTL preferences that allows users to select the language that the YouTube chat UI uses.

**Additional context**
Suggested by gvarph on Discord

**Comment by gvarph** [comment]
Another possible solution would be to somehow get the user language from youtube itself but I don't know what would be more difficult to implement.

**Comment by Candygoblen123** [comment]
duplicate of #199, closing
