### ISSUE TITLE
Add an option to include custom language/translation tags

### ISSUE THREAD

**Issue by rkn45** [LiveTL/LiveTL#156]
**Describe the solution you'd like**
Add an option that allows you to add your custom language/TL tags for the extension to filter out/use for autoprefixes. Some of translators use tags like [Trans/trans] on some VTuber channels.

**Describe alternatives you've considered**
As an alternative for now, I just manually add translator usernames to the user filter.

**Additional context**
![Example 1](https://user-images.githubusercontent.com/37614865/107242404-fa02c680-6a3c-11eb-94b0-79cdadf55366.png) 
![Example 2](https://user-images.githubusercontent.com/37614865/107242441-07b84c00-6a3d-11eb-96ab-c1234f790a59.png)

**Comment by KentoNishi** [comment]
Good idea, will put on roadmap
I wonder if allowing custom tags would diversify user tags even more and spawn a whole new world of arbitrary tags, but imma bet on it being fine and go with it

**Comment by Candygoblen123** [comment]
> Good idea, will put on roadmap
> I wonder if allowing custom tags would diversify user tags even more and spawn a whole new world of arbitrary tags, but imma bet on it being fine and go with it
I think most people would want to go with the defaults anyway, so they appear on more people's screens.  Having the ability to add custom tags will just enable viewers to be able to catch TLs from people that refuse to use a standard one.

**Comment by kmarple1** [comment]
Seconding this request. The [LORE] tag has become common on Haachama's recent streams, so I'd like to capture it as well.

**Comment by KentoNishi** [comment]
I've been quite hands off the past few weeks but I'll make sure it gets implemented before the next major update

**Comment by KentoNishi** [comment]
This is now done!
