### ISSUE TITLE
Edit / remove items from whitelists, blacklists and filters

### ISSUE THREAD

**Issue by kmarple1** [LiveTL/LiveTL#165]
**Is your feature request related to a problem? Please describe.**
Description: Currently it seems like you can easily add translation tags and username filters, but there doesn't seem to be any way to edit or remove them.

**Describe the solution you'd like**
Ideal Solution: It would be nice to be able to see a list of all current filters and individually edit or remove entries.

**Describe alternatives you've considered**
Alternatives Considered: If editing is too much work, removing entries should at least be possible.

**Comment by KentoNishi** [comment]
Done in the next update!
