### ISSUE TITLE
Hyperchat stops showing new messages a few seconds into VOD on mobile

### ISSUE THREAD

**Issue by yousie642** [LiveTL/LiveTL#168]
**Describe the bug**
On VODs, the new Hyperchat seems to stop showing new chat messages a few seconds after starting the video. Seems to work fine on live streams. I know the default YouTube chat has a similar problem, but it would only happen to me when skipping around the video. Except the mobile version of the app doesn't have an option to disable Hyperchat. 

**To Reproduce**
1. Share video to LiveTL. Sample VOD: https://youtu.be/2GO94ptRETM
2. Start video
3. Chat messages start coming on, but stop shortly after. 

**Expected behavior**
Chat should continue showing new messages

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Moto G5 Plus
 - OS: Android 10
 - Browser: n/a
 - Version: 5.0.6

**Additional context**

**Comment by KentoNishi** [comment]
I hate to use this as an excuse, but a native implementation of the app is coming soon, so stay tuned for that!

In terms of using the app in its current state, just scrubbing around in the vod works on my phone (Pixel 3a, Android 10).

**Comment by KentoNishi** [comment]
Closing due to Android rewrite
