### ISSUE TITLE
Hyperchat stops autoscrolling

### ISSUE THREAD

**Issue by thespeech** [LiveTL/LiveTL#169]
**Describe the bug**
Hyperchat randomly stops autoscrolling during a livestream.

**To Reproduce**
Happens whether the window is in-focus or out of focus. Once, it happened a second after clicking the blue down-arrow to scroll to the bottom of chat during a live-stream.

**Expected behavior**
Chat should be autoscrolling unless explicitly scrolled up once.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 89.0.4389.114 (Official Build) (64-bit)

**Comment by KentoNishi** [comment]
Fixed in the next update. Issue was that elements thst load dynamically (ex. Emotes) were taller than the rest of the message, extending the scrollable space
