### ISSUE TITLE
Captions not updating on the Chrome extension page

### ISSUE THREAD

**Issue by TheFeelTrain** [LiveTL/LiveTL#170]
**Describe the bug**
Even though LiveTL is picking up translations just fine, the captions do not get updated.

**Screenshots**
![Screenshot_20210410_202446](https://user-images.githubusercontent.com/12601452/114291293-220da680-9a3b-11eb-83de-bdf7ceed64c8.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: Brave 1.21.76 (Chromium: 89.0.4389.86)
 - Version: Chrome Extension 5.0.6

**Additional context**
No errors in the development console, and everything else seems to be working fine. I have also noticed the captions update *once* when someone with a Russian name said "dragon noises". The captions were then stuck on "dragon noises" for several minutes until I reloaded the page.

**Comment by Candygoblen123** [comment]
this is an issue because thee author is a mod, this is a known issue, and should be fixed with the ongoing extension rewrite.

**Comment by TheFeelTrain** [comment]
Wow that was quick. Well good to know it's not something on my end at least. Thanks!
