### ISSUE TITLE
Mod messages with tags aren't parsed or treated as captions

### ISSUE THREAD

**Issue by kmarple1** [LiveTL/LiveTL#172]
As you can see in the attached image, when a mod is doing translations for a stream, the tags aren't removed and the comments don't register as captions.

![image](https://user-images.githubusercontent.com/8404056/115132912-fb66e700-9fc9-11eb-97f3-60ab1e262a0c.png)

**Comment by Candygoblen123** [comment]
Should be fixed in upcoming release.
