### ISSUE TITLE
Weird scroll in ff

### ISSUE THREAD

**Issue by KentoNishi** [LiveTL/LiveTL#174]
https://user-images.githubusercontent.com/38841491/115736784-699c0880-a340-11eb-80ef-2347cd0fca43.mp4

**Comment by r2dev2** [comment]
Leads on the situation:

![image](https://user-images.githubusercontent.com/50760816/115943153-24bcc280-a463-11eb-8a40-53e7f182e7a6.png)

It seems to be a render callback in svelte/internal/index.mjs that triggers the scroll. I am not quite sure however how a callback within an iframe is causing the parent page to scroll.

**Comment by r2dev2** [comment]
Another lead: it seems that when text direction is top, the scroll issue goes away. It also scrolls whenever it catches a new translation, this seems to be an issue with auto-scroll.
