### ISSUE TITLE
Translator Mode

### ISSUE THREAD

**Issue by KentoNishi** [LiveTL/LiveTL#188]

**Comment by Hughp135** [comment]
Not sure what was intended by this, but a pretty nice feature would be to pre-fill the chat bar with the language tag after sending a message. E.g. if the translator is translating to english, automatically prefix the chat input with `[EN] ` after sending the last message. This saves a few clicks, especially if the translator is typing it in / copy pasting it from somewhere manually every time.

**Comment by Candygoblen123** [comment]
This is like, the big feature of out next major release. 

> a pretty nice feature would be to pre-fill the chat bar with the language tag after sending a message

This was a thing in the old LiveTL, but never got added back. You can add it if you want.

**Comment by r2dev2** [comment]
Just want to add, I'm working on a more extensive translator mode which has macros and omnicomplete.

**Comment by ChrRubin** [comment]
Closing since the PR has been merged.
