### ISSUE TITLE
Chat Portrait Mode missing

### ISSUE THREAD

**Issue by wrov** [LiveTL/LiveTL#207]
Pre-redesign the LiveTL config pane contained three chat location options: left, right and portrait. 

The post-redesign configs are missing the portrait option. 

The portrait option is crucial to using LiveTL on a monitor pivoted to portrait mode.
![Unbenannt](https://user-images.githubusercontent.com/13869500/117709779-9e79dd80-b1d1-11eb-9f28-c0468ded1c3a.png)

Btw, if I may make a request: Having an automatic mode, based on window width, as an additional option would be great. Having to manually switch between landscape and portrait when moving the browser between monitors is suboptimal. 

Browser: Chrome on Windows
LiveTL version: 6.0.16

**Comment by KentoNishi** [comment]
i will add in vertical mode in a future update. sorry bout that

**Comment by wrov** [comment]
Thank you very much!

**Comment by KentoNishi** [comment]
Added in the newest build, look out for an update in a few days
