### ISSUE TITLE
Fullscreen mode with shortcut not working correctly

### ISSUE THREAD

**Issue by Noobfortress** [LiveTL/LiveTL#212]
When pressing 'F' to go to fullscreen, the chat & translation panels aren't visible.
Fullscreen works as intended when clicking the fullscreen button, but using the shortcut key doesn't.

I'm using Firefox, haven't tested this in any other browsers

**Comment by KentoNishi** [comment]
idk if we can prevent certain keystrokes from being caught by the player but i'll look into it sometime
