### ISSUE TITLE
No way to open stream in LiveTL after using Embedded TLs

### ISSUE THREAD

**Issue by Hughp135** [LiveTL/LiveTL#221]
If you click on 'Embed TLs', there is no way to open the full LiveTL view without reloading the page. This creates a 'dead end' trap where there is no easy way to change between embedded/ full view unless you refresh the page or hit the browser back button.

The UX from the start should be more intuitive to a first time user, who may not know what 'Embed TLs' and 'Open LiveTL' even do.

![image](https://user-images.githubusercontent.com/12624925/119591833-3b8e6600-bdcf-11eb-8f8d-2ec6d60e5237.png)

**Comment by KentoNishi** [comment]
you can actually just hide the chat and re-open it lol

**Comment by KentoNishi** [comment]
but ye i'll add some back button ig

**Comment by Hughp135** [comment]
> you can actually just hide the chat and re-open it lol

even if that's a solution, it's not a good one (for first newer users)

**Comment by Hughp135** [comment]
> but ye i'll add some back button ig

Rather than a back button, it might be even better to have a button somewhere in the embedded view which goes to the full view with 1 click. e.g. right next to next to the settings icon you could add one like:

![image](https://user-images.githubusercontent.com/12624925/119592666-d2a7ed80-bdd0-11eb-8634-f70968a3a9e2.png)
