### ISSUE TITLE
Ability to hide New Updates popup until next update

### ISSUE THREAD

**Issue by Hughp135** [LiveTL/LiveTL#224]
The 'New Updates' popup coming every time you start LiveTL ends up being a hinderance to user experience, and may even cause people to be less interested in actually reading it (it becomes a habit to close it automatically, due to the frequency at which it appears, so people end up ignoring new updates and closing it anyway). It should only really be shown once after every new update.

First idea is to add a 2nd button next to 'Let's go', or just replace that button with a new button, which hides the popup and doesn't show it again until the next update. This button text could be "Got it/ Don't tell me again" or something similar, to avoid complicating things. If the user just clicks the 'X' button, the current behaviour can stay (e.g. the popup shows again next time).

![image](https://user-images.githubusercontent.com/12624925/119914693-ae771880-bf58-11eb-8d80-d9c9b211c90f.png)

**Comment by Candygoblen123** [comment]
Does this happen in the store build?

**Comment by r2dev2** [comment]
Uhhh, it's supposed to hide until next update if you push let's go, the x, or outside the box.
