### ISSUE TITLE
Thank the translators system

### ISSUE THREAD

**Issue by r2dev2** [LiveTL/LiveTL#225]
**Is your feature request related to a problem? Please describe.**
It would be nice if translators could receive arigadankeschons from thankful viewers and see them in one place.

**Describe the solution you'd like**
Users can have a slash command in the youtube chat entry box of ``/thank {translator}`` and messages from here show up in a pane of the translator's LiveTL filters. Thankful messages can have a sequence of invisible characters after them to make it easier to filter these messages.

**Additional context**
The slash commands should use some of the code that will be used in translator mode slash commands.

**Comment by Hughp135** [comment]
if the intention is to use youtube chat, why not just filter all @ you messages into the translations box? (also, this requires us to detect the current user's username, if such a function doesn't exist yet)

**Comment by r2dev2** [comment]
Oh good idea to detect user's username. Getting the current username should be possible through using the content scripts to send the username with postMessage.
![image](https://user-images.githubusercontent.com/50760816/120048186-4877a900-bfcb-11eb-8e8d-4530b7a63ff4.png)

**Comment by r2dev2** [comment]
Maybe far in the future if we have nothing better to do
