### ISSUE TITLE
Translation tag not filtered out

### ISSUE THREAD

**Issue by r2dev2** [LiveTL/LiveTL#229]
**Describe the bug**
The translation tag should be filtered out in the display, however, it does not get filtered out.

**To Reproduce**

Send a chat message of ``[en] hello there``.

![image](https://user-images.githubusercontent.com/50760816/120095109-e016ed80-c0d8-11eb-9d19-e30644400736.png)

**Expected behavior**
``hello there`` should have been displayed instead of ``[en] hello there``.

**Additional context**
The bug was introduced in #226 by displaying each part of a messageArray instead of the filtered text. A potential solution is to parse translation on the first part of the text so the translation tag gets removed.

**Comment by ChrRubin** [comment]
Whoops my bad, I'll look into it if no one else is.
