### ISSUE TITLE
New Update dialog keeps showing on Firefox

### ISSUE THREAD

**Issue by ChrRubin** [LiveTL/LiveTL#240]
**Describe the bug**
The fix for #224 does not seem to work for Firefox, as the dialog keeps appearing on "extension launch" even after dismissing it.

**Steps to Reproduce**
1. Open a stream with LiveTL on Firefox.
2. Close the New Update dialog.
3. Close the first stream and open another stream

**Expected behavior**
New Update dialog to be hidden until the next update.

**Desktop information (please complete the following information):**
 - OS name and version: Windows 10 20H2
 - Browser: Firefox
 - Browser Version: 89.0 and Dev 90.0b5

**Additional context**
Interestingly, the commit that fixed #224 seemed to have "worsened" the original bug on Firefox. 

On build 6.2.2 (before the fix), the New Update dialog will be hidden until next update if the user pressed the "Let's Go" button, and the bug only occurs if the user pressed 'X' or outside the dialog, no matter on Chromium or Firefox. 

With the fix in place, the New Update dialog will always get shown on Firefox regardless of how it was dismissed. The fix does however seem to be working fine on Chromium.

**Comment by r2dev2** [comment]
I sent this in discord, but I can't seem to replicate this.

https://user-images.githubusercontent.com/50760816/122624370-b6f0d980-d054-11eb-87c4-b9ea0d68fbbd.mp4

**Comment by r2dev2** [comment]
Seems like something unknown fixed it.

**Comment by dtfinch** [comment]
"New Update" still pops up every time for me in the TL Popout. 6.3.5 on Firefox 89. It doesn't matter whether I close it with the X or with "Let's Go". Even closing and reopening the popout on the same stream, it pops up again every time.
Extension storage has both v0-alpha$$lastVersion="6.3.5" and v0-alpha$$welcomeDismissed="true"

**Comment by ChrRubin** [comment]
To clarify what r2 meant, the issue is fixed in the latest dev build. It was last publicly present on 6.3.5, and an update hasn't been pushed yet.

**Comment by ChrRubin** [comment]
So this issue popped back up on v6.4.0, and I've found that this only occurs when the extension is loaded from the zip archive, and is non-existent when the extension is extracted.

I'm extremely confused.

**Comment by r2dev2** [comment]
Bruh
