### ISSUE TITLE
A "Check All" box when selecting messages for the "Screenshot" function

### ISSUE THREAD

**Issue by Clive374** [LiveTL/LiveTL#241]
**Is your feature request related to a problem? Please describe.**
It's rather tedious to have to manually click every single message one by one, when your someone like me who typically has the stream on in the background, and reads the TLs at the end or after the fact to better understand the goings on during the stream

**Describe the solution you'd like**
Either a button or checkbox like the ones used to select individual messages placed either at the start of the message log, or somewhere along the top or bottom of the UI while selecting messages to screenshot

**Describe why this solution should be included in LiveTL**
A general QoL addition that could make use of this function must faster

**Describe alternatives you've considered**
Already mentioned above, but as long as it gets the job done, that's what's important

**If this is suggesting a change to LiveTL's UI, provide documentation for why this change should be made**
Since this is more on the scale of a small addition request, i'm not entirely sure if this qualifies for me to include this, but from what i can gather, the https://material.io/components/checkboxes#usage link included in the example fits here 

**Additional context**
it may have been a long while since I last coded, but I know how complicated even seemingly simple features can be, so if this turns out to be more trouble then its worth, then don't fret over it

**Comment by KentoNishi** [comment]
Not too hard, will do
