### ISSUE TITLE
MCHAD Live Integration doesn't work

### ISSUE THREAD

**Issue by r2dev2** [LiveTL/LiveTL#255]
![image](https://user-images.githubusercontent.com/50760816/124971524-274ca400-dfde-11eb-8cc4-2230342b9615.png)

LiveTL is pulling Taishi's translations from the chat instead of from mchad api.

**Comment by KentoNishi** [comment]
While ur at it, u should make it so each mchad user is bannable individually instead of switching off the entire api

**Comment by KentoNishi** [comment]
If taishi and another tl are translating at once or someone comes in and translates the vod after a livetl did it live, it would be best if hiding one is possible

**Comment by r2dev2** [comment]
> While ur at it, u should make it so each mchad user is bannable individually instead of switching off the entire api

This won't be a problem since we only draw from a single room when a room is found.

**Comment by r2dev2** [comment]
It got fixed somewhere
