### ISSUE TITLE
Remove mod deleted messages from filtered output

### ISSUE THREAD

**Issue by ChrRubin** [LiveTL/LiveTL#269]
With the new messaging system in place LiveTL now has access to author ban and message deletion actions. Removing them from the filtered output should help out whenever there are chat mods dealing with spammers who misuse TL tags.

**Comment by ChrRubin** [comment]
@KentoNishi @r2dev2 for this do you guys think its better to mimic YTC/HC and replace the text with what YTC provides or just hide/remove the message outright?

Also I can't assign this to myself cause I don't have the required permissions lol.

**Comment by r2dev2** [comment]
Aight I gave you the perms to assign issues. I think maybe we can have a settings toggle with three options:
1. always delete
2. always show `[message deleted]`
3. prompt me if I want to delete all yeeted messages
