### ISSUE TITLE
MCHAD translation appears on initial load even when location in video is somewhere else

### ISSUE THREAD

**Issue by r2dev2** [LiveTL/LiveTL#273]
When your video progress is in the middle and you open LiveTL, the first mchad translation may appear.

## Reproduction

1. Go to [Oga's 3d debut](https://www.youtube.com/watch?v=Hw7WqfV7H0c)
2. Go to a timestamp in the middle and hit pause
3. Click open in embed
4. Wait for the translation at 2:10 to appear

## Other

* Reported by Taishi from discord

**Comment by KentoNishi** [comment]
mchad is no more o7
