### ISSUE TITLE
Reconnect to mchad/api on connection fail/disconnect

### ISSUE THREAD

**Issue by ChrRubin** [LiveTL/LiveTL#274]
LiveTL occasionally fails to connect to mchad, citing a missing `Access-Control-Allow-Origin` header even though the response does contain the said header. The connection can also sometimes be interrupted and disconnect mid-stream, causing any new TLs to stop coming through mchad. Currently, the only way to confirm that the connection failed is by looking at the web console, and refreshing the page in an attempt to fix it.

I suggest adding a reconnect feature whenever the connection drops, whether it be automatically within the scripts, or manually via a "failed to connect" indicator and a reconnect button.

Relevant screenshots:

![image](https://user-images.githubusercontent.com/20059164/127092072-f773b012-a146-4cde-a423-6771eccb0fa8.png)

![image](https://cdn.discordapp.com/attachments/780941139871531028/864825577592717332/unknown.png)

**Comment by r2dev2** [comment]
https://github.com/fanout/reconnecting-eventsource may be of interest to this issue.
