### ISSUE TITLE
Source mchad translations from the selected language.

### ISSUE THREAD

**Issue by r2dev2** [LiveTL/LiveTL#279]
Right now, all mchad translations will be shown regardless of language. This is becoming a larger problem as there are now mchad translators translating streams into languages other than english.

**Comment by r2dev2** [comment]
We will wait until all translators put their language in the mchad tags.

**Comment by ChrRubin** [comment]
This should already be implemented in #354 yeah?

**Comment by KentoNishi** [comment]
yessir
