### ISSUE TITLE
Add an option to temporarily hide translators

### ISSUE THREAD

**Issue by kmarple1** [LiveTL/LiveTL#281]
**Checklist (make sure you do all these before you submit a bug report)**
- [x] This is an issue for LiveTL, not Hyperchat. I will go to [the Hyperchat repo](https://github.com/LiveTL/HyperChat) to report an issue for Hyperchat.
- [x] This is an issue for the LiveTL web extension, not LiveTL iOS or LiveTL Android. I will go to the [iOS](https://github.com/LiveTL/ios) or [Android](https://github.com/LiveTL/android) repo to report issues for those platforms.
- [x] I have checked for a duplicate or similar issue. I made sure to check closed issues as well. 
- [x] I am not reporting a bug. If I am, I will use the bug report issue template.
- [x] I understand that I am not maintaining this codebase, and my suggestion may be rejected for any reason, including "We don't really feel like it" or "That's a little out of scope for this project" (We accept most suggestions, though.)
- [x] I also understand that even if we do accept your suggestion, it may be removed from the extension at any time, for any reason, without notification. It might not make it to a release version of the extension. 

**Is your feature request related to a problem? Please describe.**
Recently I've watched some streams with upwards of half a dozen translators. This gets... cluttered, to say the least. Mchad compounds this, as some of the translations show up twice, once with an Mchad tag and once without. Note that these are all legit translators and having their translations visible may be extremely helpful on other streams. Therefore, permanently blocking them is *not*  a good solution.

**Describe the solution you'd like**
What I would like to see is the option to temporarily hide a translator, blacklisting them from the current LiveTL instance, but *not permanently*. 

**Describe why this solution should be included in LiveTL**
This would allow the overwhelming number of translations to be cut down when many translators are present without hurting situations where only one or two are present.

**Describe alternatives you've considered**
Alternatives might include the ability to temporarily turn off LiveTL's internal parsing (allowing you to rely entirely on, say, Mchad TLs) or temporarily view only a single translator, though this is just a variation on my suggested solution.

**Comment by ChrRubin** [comment]
This is something we are already planning to work on (#272).

Also, the mchad duplication bug should be fixed on the latest version that was just released a few hours ago.

**Comment by kmarple1** [comment]
Ah, OK. I wasn't clear what was meant by "isolate translators" in #272.
