### ISSUE TITLE
Auto hide spam messages/suppress succesive message within time period

### ISSUE THREAD

**Issue by Nandaka** [LiveTL/LiveTL#283]
**Checklist (make sure you do all these before you submit a bug report)**
- [x] This is an issue for Hyperchat, not LiveTL. I will go to [the LiveTL repo](https://github.com/LiveTL/LiveTL) to report an issue for LiveTL.
- [x] I have checked for a duplicate or similar issue. I made sure to check closed issues as well. 
- [x] I am not reporting a bug. If I am, I will use the bug report issue template.
- [x] I understand that I am not maintaining this codebase, and my suggestion may be rejected for any reason, including "We don't really feel like it" or "That's a little out of scope for this project" (We accept most suggestions, though.)
- [x] I also understand that even if we do accept your suggestion, it may be removed from the extension at any time, for any reason, without notification. It might not make it to a release version of the extension. 

**Is your feature request related to a problem? Please describe.**
I notice that spam messages usually send multiple messages in quick succession, and sometimes they misuse the prefix for auto-tl. I'm not sure if the deleted messages still shown in the translation section.
![image](https://user-images.githubusercontent.com/836867/126875177-46b6d00c-667e-4271-bb71-01c12d4305d7.png)
Screenshot taken from `https://www.youtube.com/watch?v=4p2BaQ9WRzo`

**Describe the solution you'd like**
A way to automatically ignore and hide the messages if the message is sent by the same user within the certain number of time, e.g. 3 successive messages within 500ms? maybe configurable in Filter tab?

**Describe why this solution should be included in Hyperchat**
This will improve the quality-of-live of the chat and translation (for live-tl part).

**Describe alternatives you've considered**
manually add the user/bot to the blocklist, but this is not maintainable especially the bot keep come up with new username.

**If this is suggesting a change to LiveTL's UI, provide documentation for why this change should be made**
N/A

**Discord**
N/A

**Additional context**
N/A

**Comment by r2dev2** [comment]
This may be out of scope for now, but maybe we could also add a `report anti` button where it gets sent to some trusted people like Shrek Wazowski who tls Hachama for spam review?

**Comment by KentoNishi** [comment]
Inb4 I get distracted and train a spam detection model next year

**Comment by r2dev2** [comment]
> Inb4 I get distracted and train a spam detection model next year

There are actually language inference npm packages and we can just say "if we detect there's chinese and the user doesn't have chinese enabled, we yeet the message"

**Comment by Nandaka** [comment]
> 
> 
> > Inb4 I get distracted and train a spam detection model next year
> 
> There are actually language inference npm packages and we can just say "if we detect there's chinese and the user doesn't have chinese enabled, we yeet the message"

It won't really works, because the spammer do use japanese (on coco stream) or sometime english, and for SEA viewer sometime have Chinese Simplified enabled.

That why I propose based on the message frequency (as they usually using a bot, so the interval between messages usually very short, as they are going to be banned by admin ASAP), especially if you can check if the slow mode is enabled or not (somehow YT never fix this bug)...
