### ISSUE TITLE
The default caption "Captions captured from the chat will appear here..." keeps appearing after translations

### ISSUE THREAD

**Issue by priprii** [LiveTL/LiveTL#284]
This just started happening today, I assume the latest update broke something.

Prior to this, that caption would only appear the first time when the page is loaded, but now it's appearing after every TL note is displayed.

I'd suggest adding an option to the Settings for toggling the ability to move the caption instead of displaying it on page load, as it gets in the way of the seekbar for the first few seconds and people don't need to be reminded that they can move it, it really only needs to show the first time the addon is installed.

Win10 21H1, Firefox Nightly 92.0a1

I have tested with all other addons disabled.

**Comment by KentoNishi** [comment]
@r2dev2 @ChrRubin potentially got something to do with the pipeline and/or the ytc source

**Comment by ChrRubin** [comment]
@priprii Do you mean that every time a TL is caught, instead of the TL being shown in captions, the default caption is showed instead for all TLs?

**Comment by r2dev2** [comment]
Can you take a video of what you mean? I can't seem to replicate on latest develop so the problem might have been fixed.

https://user-images.githubusercontent.com/50760816/128054029-b5de80c0-65e8-4c56-b13b-717b5a9fb8e5.mp4

**Comment by r2dev2** [comment]
I can't seem to replicate what I think you mean on v6.5.3

https://user-images.githubusercontent.com/50760816/128055244-a48cc3ad-ace8-4e4b-9565-ae9f895e0e21.mp4

**Comment by priprii** [comment]
I've uninstalled and reinstalled the addon and restarted browser/PC, the addon version is 6.5.3, problem still exists.

The only settings I've changed in the addon settings are:

- Enabled "Make captions disappear when inactive"
- Disabled "Show screenshot and download buttons"
- Disabled "Show fullscreen button"

As you can see in the below video, TL captions show up one after another working normally, but then that default message shows whenever the caption is intended to set to hidden state from the "Make captions disappear when inactive" option, and any new TL captions won't show until the hidden state interval is triggered again.

Edit: I just tested with the "Make captions disappear when inactive" option disabled and the issue still exists so I guess it's not that. 

https://user-images.githubusercontent.com/41253973/128100004-cd11f7f4-ddcc-4880-ba41-66141b2379de.mp4

**Comment by ChrRubin** [comment]
Successfully reproduced it with that specific VOD. 

@r2dev2 it might have something to do with deduplication/mchad, I turned off mchad and the captions seems to be working as expected now.
