### ISSUE TITLE
Livestream timestamps are off

### ISSUE THREAD

**Issue by KentoNishi** [LiveTL/LiveTL#303]
![image](https://user-images.githubusercontent.com/38841491/129420444-db0dc593-ada0-4627-9f2f-e3a556779e1a.png)
![image](https://user-images.githubusercontent.com/38841491/129420455-50835aae-47c4-47ad-828d-b3ca93904099.png)

she hasn't been streaming for 14 hours

**Comment by ChrRubin** [comment]
YTC timestamps for live streams shows the user's current PC time, I changed it to HH:MM:SS when fixing #282.
