### ISSUE TITLE
Typing single letters triggers prefix macro

### ISSUE THREAD

**Issue by Mojken** [LiveTL/LiveTL#328]
While the prefix macro is on, typing single letters (such as the words 'a' or 'I') followed by a space causes it to expand into a language tag. In my case, I only have one set up with the command `/en`, and all single letters expand into "[en]". Changing the macro string does change the result of single letter expansions as well. No symbols except my macro prefix / exhibit the same behaviour, changing the macro prefix results in / not being expanded.

**Comment by KentoNishi** [comment]
@Mojken could you copy-paste ur exported settings json and send it here?

**Comment by Mojken** [comment]
Sure thing
> {"language":"English","showModMessage":true,"chatZoom":1.0025,"showTimestamp":true,"textDirection":"BOTTOM","videoSide":"LEFT","showCaption":true,"captionDuration":10,"captionFontSize":18,"captionWidth":30.723149336756524,"captionLeft":23.919554985023534,"captionTop":85.06444275966642,"doSpeechSynth":false,"speechVolume":1,"doTranslatorMode":true,"videoPanelSize":88.9453125,"chatSize":43.87755102040816,"livetlFontSize":18,"textFilters":[],"textBlacklist":[],"plaintextWhitelist":[],"plaintextBlacklist":[],"userFilters":{},"channelFilters":{},"plainAuthorWhitelist":[],"regexAuthorWhitelist":[],"plainAuthorBlacklist":[],"regexAuthorBlacklist":[],"customFilters":[],"enableCaptionTimeout":true,"chatSplit":"HORIZONTAL","lastVersion":"6.7.2","screenshotRenderWidth":500,"welcomeDismissed":true,"macros":[{"name":"l","expansion":"[en]","enabled":false}],"doAutoPrefix":false,"enableMchadTLs":true,"enableAPITLs":true,"enableExportButtons":true,"enableFullscreenButton":true,"mchadUsers":{"toxr95 KR":true},"autoPrefixTag":"[$filterLang]","macroTrigger":"t","ytcDeleteBehaviour":"HIDE","autoVertical":true,"enableSpamProtection":true,"spamMsgAmount":4.970000000000001,"spamMsgInterval":9.91,"spammersDetected":{},"speechSpeed":1}

**Comment by r2dev2** [comment]
I'll fix this @KentoNishi
