### ISSUE TITLE
Messages with only emojis never gets filtered

### ISSUE THREAD

**Issue by ChrRubin** [LiveTL/LiveTL#331]
Messages that only contain emojis do not contain any text and will never be shown by the LiveTL output, since the text property is required in the messages stores.

This can be undesirable when LiveTL is set to show all mod/owner messages (or even custom user filters), but messages from these users do not get filtered when it only contains emojis.

**Comment by r2dev2** [comment]
Maybe in the ``ytcToMsg``, we can have it set text to an [invisible character](https://c.r74n.com/invisible) if it detects emojis?

**Comment by Eroxl** [comment]
Is there a reason we can't just remove the null string check for all messages besides the moderator messages? 
I don't think moderators sending white space will be that much of an issue.

Like just changing this (line 61 in sources.js) :
```javascript
return ytc.subscribe(message => {
  if (!message || isBlacklisted(message)) return;
  const text = message.text.trim();
  const parsed = parseTranslation(text);

  if (!text) return;
  if (isTranslation(parsed)) {
    setTranslation(replaceFirstTranslation(message), parsed.msg);
  } else if (isWhitelisted(message)) {
    setTranslation(message);
  } else if (showIfMod(message)) {
    setModMessage(message);
  }
});
```
To something like this :
```Javascript
return ytc.subscribe(message => {
  if (!message || isBlacklisted(message)) return;
  const text = message.text.trim();
  const parsed = parseTranslation(text);

  if (text && isTranslation(parsed)) {
    setTranslation(replaceFirstTranslation(message), parsed.msg);
  } else if (text && isWhitelisted(message)) {
    setTranslation(message);
  } else if (showIfMod(message)) {
    setModMessage(message);
 }
});
```

**Comment by KentoNishi** [comment]
If I recall correctly, this was done to prevent some false positive cases when the filter fires but the text attached to the filtered message is empty. I *think* we can just add a test case for emoji-only messages and that'll do the trick

Ping @r2dev2

**Comment by r2dev2** [comment]
@KentoNishi No, @Eroxl is correct and the logic there was wrong. His or her change removes the empty text check from mod message detection which is a good fix to the issue.

@Eroxl can you make a pr with that change?

**Comment by Eroxl** [comment]
@r2dev2 Ok i just submitted the pull request if you want to check it out #357
