### ISSUE TITLE
Auto-embed TLs

### ISSUE THREAD

**Issue by 01-1** [LiveTL/LiveTL#345]
**Is your feature request related to a problem? Please describe.**

In ytcfilter, the chat filter is always active. I'd like this to be available in LiveTL as an option.

**Describe the solution you'd like**

I would like to have LiveTL automatically embed TLs when opening a stream (this would be a toggleable option, probably in settings somewhere).

**Describe why this solution should be included in LiveTL**

Automatically doing the embed TLs is much easier because it saves a click. Also, you won't miss TLs by forgetting to click the button.

**Describe alternatives you've considered**

The only alternatives would be using ytcfilter or a separate extension.

**If this is suggesting a change to LiveTL's UI, provide documentation for why this change should be made**

Not really a UI change, IDK about that part

**Comment by KentoNishi** [comment]
This is coming in the very next update!
![image](https://user-images.githubusercontent.com/38841491/134119916-e40a18ca-e282-400f-baad-b6d7a0fccd5d.png)

**Comment by r2dev2** [comment]
The update has been submitted for chrome store review and is currently live on Firefox :rocket:

**Comment by 01-1** [comment]
uhh idk why but the auto launch doesnt work (on firefox), it only works in like a specific scenario where i use inspect element and have the chat hide and reshow

**Comment by 01-1** [comment]
it's probably an issue with my specific setup, (linux+firefox) I tried disabling some extensions but I don't think it's any of them

**Comment by r2dev2** [comment]
Oh shoot it doesn't work with my firefox on arch linux either. Re-opening.

It's probably because we're checking whether to launch the thing before storage loads. I shall investigate.
