### ISSUE TITLE
Use New Issue Forms

### ISSUE THREAD

**Issue by lithomas1** [LiveTL/LiveTL#350]
**Checklist (make sure you do all these before you submit a bug report)**
- [x] This is an issue for LiveTL, not Hyperchat. I will go to [the Hyperchat repo](https://github.com/LiveTL/HyperChat) to report an issue for Hyperchat.
- [x] This is an issue for the LiveTL web extension, not LiveTL iOS or LiveTL Android. I will go to the [iOS](https://github.com/LiveTL/ios) or [Android](https://github.com/LiveTL/android) repo to report issues for those platforms.
- [x] I have checked for a duplicate or similar issue. I made sure to check closed issues as well. 
- [x] I am not reporting a bug. If I am, I will use the bug report issue template.
- [x] I understand that I am not maintaining this codebase, and my suggestion may be rejected for any reason, including "We don't really feel like it" or "That's a little out of scope for this project" (We accept most suggestions, though.)
- [x] I also understand that even if we do accept your suggestion, it may be removed from the extension at any time, for any reason, without notification. It might not make it to a release version of the extension. 

**Is your feature request related to a problem? Please describe.**

LiveTL should migrate to using the new issue forms. https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms In general, they are a big improvement over the markdown based templates(i.e. having dropdown menus, required fields, etc.)

**Describe the solution you'd like**

LiveTL should migrate to using the new issue forms.

**Describe why this solution should be included in LiveTL**

See above. 

**Describe alternatives you've considered**

N/A.

cc @r2dev2 @KentoNishi

**Comment by r2dev2** [comment]
@lithomas1 can you get this done, assigning this to you
