### ISSUE TITLE
[Feature]: Stop listening to mchad room when stream ends

### ISSUE THREAD

**Issue by ChrRubin** [LiveTL/LiveTL#360]
### Checklist

- [X] This is an issue for LiveTL, not Hyperchat. I will go to [the Hyperchat repo](https://github.com/LiveTL/HyperChat) to report an issue with Hyperchat.
- [X] This is an issue for the LiveTL web extension, not LiveTL iOS or LiveTL Android. I will go to the [iOS](https://github.com/LiveTL/ios) or [Android](https://github.com/LiveTL/android) repo to report issues for those platforms.
- [X] I have checked for a duplicate or similar issue. I made sure to check closed issues as well.
- [X] I am not reporting a bug. If I am, I will use the bug report issue template.
- [X] By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/LiveTL/LiveTL/blob/develop/CODE_OF_CONDUCT.md)

### Is your feature request related to a problem? Please describe.

When a stream ends and a TLer starts TLing another stream, they remain in the same room. This causes TLs from the new stream to show up on the previous one.

### Describe the solution you'd like

Stop listening to the mchad room once the stream ends, which should be doable with the iframe API `onStateChange` event, tho some postMessaging is required for when the workaround player is used.

There's also a possibility that whenever the iframe spazzes out during the stream that `onStateChange` will return `PlayerState.ENDED`, so we probably want to re-listen to the room when `onStateChange` returns `PlayerState.PLAYING` after that.

**Comment by ChrRubin** [comment]
Actually now that I think about it this only works for LiveTL Mode and not Embed Mode and Popout Mode.

**Comment by KentoNishi** [comment]
Saw the convo in #beta-tech-support

Probably best to wait for mon's implementation of the flag

**Comment by KentoNishi** [comment]
tldex
