### ISSUE TITLE
[Bug]: Long words don't break properly

### ISSUE THREAD

**Issue by ChrRubin** [LiveTL/LiveTL#364]
### Checklist

- [X] This is an issue for LiveTL, not Hyperchat. I will go to [the Hyperchat repo](https://github.com/LiveTL/HyperChat) to report an issue with Hyperchat.
- [X] This is an issue for the LiveTL web extension, not LiveTL iOS or LiveTL Android. I will go to the [iOS](https://github.com/LiveTL/ios) or [Android](https://github.com/LiveTL/android) repo to report issues for those platforms.
- [X] This issue is not a matter of opinion. If it is, I will use the feature suggestion issue template.
- [X] I have checked for a duplicate or similar issue. I made sure to check closed issues as well.
- [X] I am still able to reproduce the issue after I reinstall the extension.
- [X] I have clear instructions to reproduce the bug, even on another machine.
- [X] I am not suggesting a feature. If I am, I will use the feature suggestion issue template.
- [X] By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/LiveTL/LiveTL/blob/develop/CODE_OF_CONDUCT.md)

### Describe the bug

Long continuous words doesn't break properly and causes the horizontal scrollbar to show, which messes up the display of all later TLs until a page refresh.

### Steps To Reproduce

1. Open any stream/VOD with TLs in any of the 3 modes.
2. Inspect the TL text and edit it to a single extremely long word without spaces.
3. Watch everything being displayed awfully when the horizontal scrollbar shows up.

(I had an actual example that doesn't include editing with DevTools but Vee edited it to no longer break lmao)

### Expected behavior

Long words should break properly without causing the horizontal scrollbar to show up.

Probably just needs the `break-words` tailwind class somewhere.

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### Anything else?

This was during the stream but Vee has since edited it:
![image](https://user-images.githubusercontent.com/20059164/144056743-660664d8-b0a5-4da3-a47d-88f4d5e2d5d4.png)

This is with editing TL text via DevTools:
![image](https://user-images.githubusercontent.com/20059164/144057327-5066f04e-260b-43d0-aca2-39e37003cf8e.png)

**Comment by KentoNishi** [comment]
shiet it's been a month since I abandoned this, I think I'll just reimplement it correctly in the notification pr cuz that one plays around with a lot of css

**Comment by ChrRubin** [comment]
Fixed in #363 (I believe)
