### ISSUE TITLE
[Feature]: Option to switch positions of YTC and filtered TLs

### ISSUE THREAD

**Issue by ChrRubin** [LiveTL/LiveTL#365]
### Checklist

- [X] This is a suggestion for LiveTL, not Hyperchat. I will go to [the Hyperchat repo](https://github.com/LiveTL/HyperChat) to suggest a feature for Hyperchat.
- [X] This is a suggestion for the LiveTL web extension, not LiveTL iOS or LiveTL Android. I will go to the [iOS](https://github.com/LiveTL/ios) or [Android](https://github.com/LiveTL/android) repo to suggest features for those platforms.
- [X] I have checked for a duplicate or similar feature request/issue. I made sure to check closed issues as well.
- [X] I am not reporting a bug. If I am, I will use the bug report issue template.
- [X] By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/LiveTL/LiveTL/blob/develop/CODE_OF_CONDUCT.md)

### Is your feature request related to a problem? Please describe.

Some people might prefer having filtered TLs on top and YTC at the bottom.

### Describe the solution you'd like

Add an option to switch the position of YTC and filtered TLs. Should work for both horizontal and vertical chat split.

**Comment by Yay295** [comment]
This option is not available when using LiveTL embedded. Is that something that can be added/enabled? Specifically the option in the settings isn't available. It seems to work if you open the popup view, change the setting, and go back to embedded.

**Comment by Eroxl** [comment]
@KentoNishi Was there a specific reason you removed it in embed mode. 

This was the commit where it was changed => https://github.com/LiveTL/LiveTL/pull/376/commits/6fa26834773dd0d48397147160ee199fdf2644d4

**Comment by KentoNishi** [comment]
no, seems to just be a mistake, imma open a new issue

**Comment by KentoNishi** [comment]
https://github.com/LiveTL/LiveTL/issues/396
