### ISSUE TITLE
[Bug]: Nondeterministic builds

### ISSUE THREAD

**Issue by r2dev2** [LiveTL/LiveTL#369]
### Checklist

- [X] This is an issue for LiveTL, not Hyperchat. I will go to [the Hyperchat repo](https://github.com/LiveTL/HyperChat) to report an issue with Hyperchat.
- [X] This is an issue for the LiveTL web extension, not LiveTL iOS or LiveTL Android. I will go to the [iOS](https://github.com/LiveTL/ios) or [Android](https://github.com/LiveTL/android) repo to report issues for those platforms.
- [X] This issue is not a matter of opinion. If it is, I will use the feature suggestion issue template.
- [X] I have checked for a duplicate or similar issue. I made sure to check closed issues as well.
- [X] I am still able to reproduce the issue after I reinstall the extension.
- [X] I have clear instructions to reproduce the bug, even on another machine.
- [X] I am not suggesting a feature. If I am, I will use the feature suggestion issue template.
- [X] By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/LiveTL/LiveTL/blob/develop/CODE_OF_CONDUCT.md)

### Describe the bug

Sometimes, `yarn start` will error out when building the extension and give the following error where it can't find many types and namespaces.

![can't find types and namespaces](https://user-images.githubusercontent.com/50760816/145449499-1684e502-04f4-4cfc-b02e-363d023367ab.png)

### Steps To Reproduce

1. `yarn start`

### Expected behavior

It  should always succeed but many times, it doesn't succeed.

### What browsers are you seeing the problem on?

Other (Put it in the "Anything else?" section)

### Anything else?

Nice app with an amazing dev team.

These errors appeared on my arch linux computer.

**Comment by ChrRubin** [comment]
Have you ran `yarn` to check and install missing deps? The YT namespace is from `@types/youtube`.

**Comment by r2dev2** [comment]
> Have you ran `yarn` to check and install missing deps? The YT namespace is from `@types/youtube`.

Yes, I ran `yarn` before this one and it said that I had all deps installed. I'll save the entire output the next time it happens, but I *think* some other types other than yt were missing as well.

**Comment by r2dev2** [comment]
I caught webpack being naughty again. [Here's the log on pastebin](https://pastebin.com/fFzu6Pzg).

**Comment by KentoNishi** [comment]
This happens to me when I save and it tries to hot reload with an error elsewhere in the code. Does this ever happen on initial build? For me it doesn't, only on save in dev mode

**Comment by ChrRubin** [comment]
> I caught webpack being naughty again. [Here's the log on pastebin](https://pastebin.com/fFzu6Pzg).

Hmm... All those errors are for types from `@types`, which should work out of the box as long as the packages are installed.

I'm real confused why it would error if all the deps are installed properly.

**Comment by KentoNishi** [comment]
haven't had this problem in a while so closing
