### ISSUE TITLE
[Bug]: TL Selection seems like it doesn't work?

### ISSUE THREAD

**Issue by KentoNishi** [LiveTL/LiveTL#378]
### Checklist

- [X] This is an issue for LiveTL, not Hyperchat. I will go to [the Hyperchat repo](https://github.com/LiveTL/HyperChat) to report an issue with Hyperchat.
- [X] This is an issue for the LiveTL web extension, not LiveTL iOS or LiveTL Android. I will go to the [iOS](https://github.com/LiveTL/ios) or [Android](https://github.com/LiveTL/android) repo to report issues for those platforms.
- [X] This issue is not a matter of opinion. If it is, I will use the feature suggestion issue template.
- [X] I have checked for a duplicate or similar issue. I made sure to check closed issues as well.
- [X] I am still able to reproduce the issue after I reinstall the extension.
- [X] I have clear instructions to reproduce the bug, even on another machine.
- [X] I am not suggesting a feature. If I am, I will use the feature suggestion issue template.
- [X] By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/LiveTL/LiveTL/blob/develop/CODE_OF_CONDUCT.md)

### Describe the bug

[Bug]: TL Selection seems like it doesn't work?

![Uploading image.png…]()

### Steps To Reproduce

![image](https://user-images.githubusercontent.com/38841491/147809378-90073acc-a411-4be2-9f76-937245bf0739.png)

### Expected behavior

actually select em

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

**Comment by ChrRubin** [comment]
Seems like its just visual, selected TLs still get exported correctly but the count doesn't get updated for some reason.
