### ISSUE TITLE
[Feature]: Twitch support

### ISSUE THREAD

**Issue by r2dev2** [LiveTL/LiveTL#379]
<details>
<summary>Checklist</summary>

- [X] This is a suggestion for LiveTL, not Hyperchat. I will go to [the Hyperchat repo](https://github.com/LiveTL/HyperChat) to suggest a feature for Hyperchat.
- [X] This is a suggestion for the LiveTL web extension, not LiveTL iOS or LiveTL Android. I will go to the [iOS](https://github.com/LiveTL/ios) or [Android](https://github.com/LiveTL/android) repo to suggest features for those platforms.
- [X] I have checked for a duplicate or similar feature request/issue. I made sure to check closed issues as well.
- [X] I am not reporting a bug. If I am, I will use the bug report issue template.
- [X] By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/LiveTL/LiveTL/blob/develop/CODE_OF_CONDUCT.md)

</details>

### Is your feature request related to a problem? Please describe.

KSON is starting Twitch.

### Describe the solution you'd like

Make LiveTL work on Twitch by converting the Twitch chat format to YouTube chat format and slapping in our interface.

### Describe alternatives you've considered

Use LiveTL lite and mchad because Taishi who translates KSON uses mchad.

**Comment by r2dev2** [comment]
[tmijs](https://github.com/tmijs/tmi.js) seems to work without CORS issues for getting twitch messages.
```js
const client = new tmi.Client({
  options: { debug: true, messagesLogLevel: "info" },
  connection: {
        reconnect: true,
        secure: true
    },
  channels: ['chess'] // change this channel
});
client.connect().catch(console.error);
client.on('message', (channel, tags, message, self) => {
    if(self) return;
    console.log(tags, message)
});
```
![tmi demo](https://user-images.githubusercontent.com/50760816/148262235-879cac59-c072-4971-87c5-f3a0a491713a.png)

**Comment by ChrRubin** [comment]
I'm tempted to just use MutationObserver so we don't need to create a separate chat connection lmao

**Comment by r2dev2** [comment]
> I'm tempted to just use MutationObserver so we don't need to create a separate chat connection lmao

That would require more code and effort than just using tmi though kek. All we need to do for twitch is just mount livetl in twitch, use mchad with the twitch stream url, and convert the tmi into a writable store of ytcmessages.

**Comment by ChrRubin** [comment]
tmi doesn't support VOD chat tho
