### ISSUE TITLE
[Bug]: "This live event is no longer available." on an ongoing stream.

### ISSUE THREAD

**Issue by gakiloroth** [LiveTL/LiveTL#382]
### Checklist

- [X] This is an issue for LiveTL, not Hyperchat. I will go to [the Hyperchat repo](https://github.com/LiveTL/HyperChat) to report an issue with Hyperchat.
- [X] This is an issue for the LiveTL web extension, not LiveTL iOS or LiveTL Android. I will go to the [iOS](https://github.com/LiveTL/ios) or [Android](https://github.com/LiveTL/android) repo to report issues for those platforms.
- [X] This issue is not a matter of opinion. If it is, I will use the feature suggestion issue template.
- [X] I have checked for a duplicate or similar issue. I made sure to check closed issues as well.
- [X] I am still able to reproduce the issue after I reinstall the extension.
- [X] I have clear instructions to reproduce the bug, even on another machine.
- [X] I am not suggesting a feature. If I am, I will use the feature suggestion issue template.
- [X] By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/LiveTL/LiveTL/blob/develop/CODE_OF_CONDUCT.md)

### Describe the bug

On one of my accounts I see this everytime I try to open the LiveTL standalone page:
![image](https://user-images.githubusercontent.com/9069768/149463613-62838b1e-443f-4c84-8cf9-95dc0bfd820d.png)

This does not happen on my other accounts, tested multiple stream (just for sanity's sake this was one of the streams I tested): https://youtu.be/nwH92DhcmDw

I tested in incognito with 3 different accounts as well on non-incognito Chrome after deleting cookies, as well as reinstalling the extension.

### Steps To Reproduce

1. Go to a stream
2. Click on this button
![image](https://user-images.githubusercontent.com/9069768/149463834-1b3ee674-1ed9-403d-92fe-deba9b200336.png)
3. If it is one of the affected accounts you will see this page:
![image](https://user-images.githubusercontent.com/9069768/149463876-950bf4a3-2bf6-48a2-aa90-a604685198ce.png)

I am unsure why only one of my 3 accounts is affected, the only difference is that it has Youtube Premium, but it's had it for months.

### Expected behavior

The LiveTL page should open with the video feed working.

### What browsers are you seeing the problem on?

Chrome

**Comment by ChrRubin** [comment]
This is a known issue that a few people have reported in the discord. It's a problem on YouTube's side that doesn't just affect us, but also any other site that uses YouTube's iframe player such as Holodex. 

From what I can tell, it seems like certain accounts are being restricted by YouTube for whatever reason to not be able to view videos/streams on the iframe player. Logging out, using incognito or blocking all cookies (not recommended) will fix the issue temporarily.

There's not much we can do on our side other than make noise to YouTube and hope they fix it.

**Comment by gakiloroth** [comment]
Comment for anyone who sees this looking for solutions: refreshing seems to eventually fix this issue for me.
