### ISSUE TITLE
[Bug]: Wrong settings page when clicking HC settings

### ISSUE THREAD

**Issue by KentoNishi** [LiveTL/LiveTL#387]
### Checklist

- [X] This is an issue for LiveTL, not Hyperchat. I will go to [the Hyperchat repo](https://github.com/LiveTL/HyperChat) to report an issue with Hyperchat.
- [X] This is an issue for the LiveTL web extension, not LiveTL iOS or LiveTL Android. I will go to the [iOS](https://github.com/LiveTL/ios) or [Android](https://github.com/LiveTL/android) repo to report issues for those platforms.
- [X] This issue is not a matter of opinion. If it is, I will use the feature suggestion issue template.
- [X] I have checked for a duplicate or similar issue. I made sure to check closed issues as well.
- [X] I am still able to reproduce the issue after I reinstall the extension.
- [X] I have clear instructions to reproduce the bug, even on another machine.
- [X] I am not suggesting a feature. If I am, I will use the feature suggestion issue template.
- [X] By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/LiveTL/LiveTL/blob/develop/CODE_OF_CONDUCT.md)

### Describe the bug

When clicking the HC settings button in LiveTL, the LiveTL options.html opens, not the HyperChat settings pane.

![image](https://user-images.githubusercontent.com/38841491/150669302-af395910-b1ae-4f17-b70a-866cca90a630.png)

### Steps To Reproduce

Click the thing lmao

### Expected behavior

The HC options page opens

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### Anything else?

@ChrRubin

**Comment by r2dev2** [comment]
![kekw](https://user-images.githubusercontent.com/50760816/150669480-484d646a-35be-45a1-9016-557ea79ea932.gif)
