### ISSUE TITLE
[Bug]: Compatibility With HyperChat Also Installed

### ISSUE THREAD

**Issue by Yay295** [LiveTL/LiveTL#394]
### Checklist

- [X] This is an issue for LiveTL, not Hyperchat. I will go to [the Hyperchat repo](https://github.com/LiveTL/HyperChat) to report an issue with Hyperchat.
- [X] This is an issue for the LiveTL web extension, not LiveTL iOS or LiveTL Android. I will go to the [iOS](https://github.com/LiveTL/ios) or [Android](https://github.com/LiveTL/android) repo to report issues for those platforms.
- [X] This issue is not a matter of opinion. If it is, I will use the feature suggestion issue template.
- [X] I have checked for a duplicate or similar issue. I made sure to check closed issues as well.
- [X] I am still able to reproduce the issue after I reinstall the extension.
- [X] I have clear instructions to reproduce the bug, even on another machine.
- [X] I am not suggesting a feature. If I am, I will use the feature suggestion issue template.
- [X] By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/LiveTL/LiveTL/blob/develop/CODE_OF_CONDUCT.md)

### Describe the bug

If both LiveTL and HyperChat are installed, no chat messages are shown.

### Steps To Reproduce

1. Install LiveTL and HyperChat.
2. Try to view the chat on a YouTube video (I didn't check Twtch).

### Expected behavior

Either the extensions detect each other and work together, or a warning message is shown telling the user to disable/uninstall HyperChat.

### What browsers are you seeing the problem on?

Chrome

**Comment by r2dev2** [comment]
We used to have a warning message but we removed it for some reason. @KentoNishi should we make pure hyperchat extension just disable itself if it detects LiveTL?
