### ISSUE TITLE
[Bug]: switch placement in embed mode

### ISSUE THREAD

**Issue by KentoNishi** [LiveTL/LiveTL#396]
### Checklist

- [X] This is an issue for LiveTL, not Hyperchat. I will go to [the Hyperchat repo](https://github.com/LiveTL/HyperChat) to report an issue with Hyperchat.
- [X] This is an issue for the LiveTL web extension, not LiveTL iOS or LiveTL Android. I will go to the [iOS](https://github.com/LiveTL/ios) or [Android](https://github.com/LiveTL/android) repo to report issues for those platforms.
- [X] This issue is not a matter of opinion. If it is, I will use the feature suggestion issue template.
- [X] I have checked for a duplicate or similar issue. I made sure to check closed issues as well.
- [X] I am still able to reproduce the issue after I reinstall the extension.
- [X] I have clear instructions to reproduce the bug, even on another machine.
- [X] I am not suggesting a feature. If I am, I will use the feature suggestion issue template.
- [X] By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/LiveTL/LiveTL/blob/develop/CODE_OF_CONDUCT.md)

### Describe the bug

``

### Steps To Reproduce

``

### Expected behavior

``

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge, Other (Put it in the "Anything else?" section)

### Anything else?

``

**Comment by Eroxl** [comment]
@KentoNishi Do you want me to fix this or are u gonna?

**Comment by KentoNishi** [comment]
@Eroxl currently in class so if u wanna do it quickly i'll go ahead and merge it for the very next production release, since i haven't released the latest build publicly yet

thx
