### ISSUE TITLE
[Bug]: Parent page scrolls to filtered message on Firefox

### ISSUE THREAD

**Issue by ChrRubin** [LiveTL/LiveTL#403]
### Checklist

- [X] This is an issue for LiveTL, not Hyperchat. I will go to [the Hyperchat repo](https://github.com/LiveTL/HyperChat) to report an issue with Hyperchat.
- [X] This is an issue for the LiveTL web extension, not LiveTL iOS or LiveTL Android. I will go to the [iOS](https://github.com/LiveTL/ios) or [Android](https://github.com/LiveTL/android) repo to report issues for those platforms.
- [X] This issue is not a matter of opinion. If it is, I will use the feature suggestion issue template.
- [X] I have checked for a duplicate or similar issue. I made sure to check closed issues as well.
- [X] I am still able to reproduce the issue after I reinstall the extension.
- [X] I have clear instructions to reproduce the bug, even on another machine.
- [X] I am not suggesting a feature. If I am, I will use the feature suggestion issue template.
- [X] By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/LiveTL/LiveTL/blob/develop/CODE_OF_CONDUCT.md)

### Describe the bug

When using Embed Mode on Firefox, `scrollIntoView` will also scroll the entire parent page to the specified element. This is especially apparent when using YouTube's theater mode, where the chat and LiveTL are off-screen.

This might be a problem with Firefox's implementation of `scrollIntoView`, based on [this currently unanswered SO post](https://stackoverflow.com/questions/70816641/scrollintoview-ancestor-frame-scrolling-in-firefox-but-not-chrome).

### Steps To Reproduce

1. Open a stream/VOD with YT theater mode.
2. Launch LiveTL in embed mode.
3. Wait for a filtered message.

### Expected behavior

The parent page doesn't scroll to the filtered message.

### What browsers are you seeing the problem on?

Firefox

### Anything else?

https://gfycat.com/ko/boldunsightlyherald

**Comment by KentoNishi** [comment]
good ol firefox
