### ISSUE TITLE
[Feature]: Filter chat messages directly

### ISSUE THREAD

**Issue by archiif** [LiveTL/LiveTL#406]
### Checklist

- [X] This is a suggestion for LiveTL, not Hyperchat. I will go to [the Hyperchat repo](https://github.com/LiveTL/HyperChat) to suggest a feature for Hyperchat.
- [X] This is a suggestion for the LiveTL web extension, not LiveTL iOS or LiveTL Android. I will go to the [iOS](https://github.com/LiveTL/ios) or [Android](https://github.com/LiveTL/android) repo to suggest features for those platforms.
- [X] I have checked for a duplicate or similar feature request/issue. I made sure to check closed issues as well.
- [X] I am not reporting a bug. If I am, I will use the bug report issue template.
- [X] By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/LiveTL/LiveTL/blob/develop/CODE_OF_CONDUCT.md)

### Is your feature request related to a problem? Please describe.

I want to be able to filter the chat by a certain language, and I've been using [Chat Filter for YouTube Live](https://chrome.google.com/webstore/detail/jalcplhakmckbmlbidmbmpaegcpbejog). But recently I've picked up HyperChat to debloat the chat and the chat filter extension won't work along with it. I'm not trying to use the chat filter for translation purposes, so the LiveTL's current UI doesn't work very well for my purposes.

### Describe the solution you'd like

If LiveTL can filter messages directly instead of just capturing them into a separate window, this can make the extension useful as a chat filter. It might also be useful for filtering spam messages which is probably going to be beneficial for a lot of users.
But if there are other chat filter extensions that can also work with HyperChat, please do tell.

**Comment by KentoNishi** [comment]
[ytcfilter](https://chrome.google.com/webstore/detail/ytcfilter/mnldnbhgfocmkehnlkeanlhfmopepnko?msclkid=04d33d35b61f11ecb4a80e2dfd290a22) exists, but it's not under active development anymore. i worked with the developer to make sure that livetl/hc and ytcfilter are fully compatible, so they should work out of the box

**Comment by archiif** [comment]
@KentoNishi If I remember correctly, ytcfilter works pretty much like LiveTL right? It captures messages based on a filter into a separate box.

**Comment by KentoNishi** [comment]
Oh I see what u mean, that isn't a thing yet. We could add that sometime

**Comment by r2dev2** [comment]
@KentoNishi if I'm understanding this correctly, it's something that we would change in https://github.com/LiveTL/HyperChat. Should we move this issue to that repo?

**Comment by archiif** [comment]
Moved to https://github.com/LiveTL/HyperChat/issues/81
