### ISSUE TITLE
[Bug]: Cannot use BetterTTV when HyperChat disabled

### ISSUE THREAD

**Issue by r2dev2** [LiveTL/LiveTL#452]
### Checklist

- [X] This is an issue for LiveTL, not Hyperchat. I will go to [the Hyperchat repo](https://github.com/LiveTL/HyperChat) to report an issue with Hyperchat.
- [X] This is an issue for the LiveTL web extension, not LiveTL iOS or LiveTL Android. I will go to the [iOS](https://github.com/LiveTL/ios) or [Android](https://github.com/LiveTL/android) repo to report issues for those platforms.
- [X] This issue is not a matter of opinion. If it is, I will use the feature suggestion issue template.
- [X] I have checked for a duplicate or similar issue. I made sure to check closed issues as well.
- [X] I am still able to reproduce the issue after I reinstall the extension.
- [X] I have clear instructions to reproduce the bug, even on another machine.
- [X] I am not suggesting a feature. If I am, I will use the feature suggestion issue template.
- [X] By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/LiveTL/LiveTL/blob/develop/CODE_OF_CONDUCT.md)

### Describe the bug

When LiveTL is installed, users are unable to launch BetterTTV settings when HyperChat is disabled.

![image](https://github.com/LiveTL/LiveTL/assets/50760816/a703ecd3-699d-41b6-b68a-7f14483dc5da)

### Steps To Reproduce

1. install livetl and betterttv
2. go to https://www.youtube.com/watch?v=jfKfPfyJRdk
3. disable hyperchat
4. click on triple dot next to hc button
5. click on launch betterttv settings

### Expected behavior

settings should launch

### What browsers are you seeing the problem on?

Firefox

### Anything else?

This may be an issue with HyperChat, not LiveTL, will analyze further.

Reported by tunnelsnakes in ltlcord

**Comment by r2dev2** [comment]
Ok so I can confirm this issue with the deployed LiveTL but the issue is not present when I build locally????????

**Comment by r2dev2** [comment]
Never mind, I can reproduce by checking out v8.3.12.

It seems however that #450 has somehow also fixed this issue?????

@KentoNishi can you release new version

**Comment by KentoNishi** [comment]
will do 2nite prolly

**Comment by KentoNishi** [comment]
https://github.com/LiveTL/LiveTL/releases/tag/v8.3.13
